despliegue

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,12 +3,12 @@ name: Mobil CI/CD Workflow
 on:
   push:
     branches:
-      - main  # Solo en la rama main
+      - main
   pull_request:
-    types: [opened, closed]  # Solo ejecuta al abrir o cerrar PR en main
+    types: [opened, closed]
     branches:
       - main
-  workflow_dispatch:  # Permite ejecutar el flujo manualmente
+  workflow_dispatch:
 
 jobs:
   build-and-upload:
@@ -41,7 +41,7 @@ jobs:
         run: npm install
 
       - name: Run Tests
-        run: npm test  # Esto ejecutará las pruebas en modo CI sin --watchAll
+        run: npm test
 
       - name: Run ESLint
         run: npm run lint --if-present
@@ -50,25 +50,27 @@ jobs:
         run: npm install -g eas-cli
 
       - name: Build APK for Android
-        if: github.ref == 'refs/heads/main'  # Ejecutar solo en la rama main
+        if: github.ref == 'refs/heads/main'
         run: eas build --platform android --profile production --non-interactive
         env:
           EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
 
       - name: Install gdrive
         run: |
-          # Actualizar y verificar espacio
           sudo apt-get update
-          df -h /  # Esto mostrará el espacio libre en disco para verificar
-
-          # Instalar wget si no está ya instalado
           sudo apt-get install -y wget
-
+          
           # Descargar y descomprimir gdrive
           wget -O gdrive.tar.gz https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_amd64.tar.gz
           tar -xzf gdrive.tar.gz
-          chmod +x gdrive
-          sudo mv gdrive /usr/local/bin/gdrive
+          
+          # Verificar que el archivo gdrive fue extraído y moverlo a /usr/local/bin
+          if [ -f "gdrive" ]; then
+            chmod +x gdrive
+            sudo mv gdrive /usr/local/bin/gdrive
+          else
+            echo "Error: gdrive no se encontró después de la extracción" && exit 1
+          fi
 
       - name: Authenticate with Google Drive
         env:
@@ -87,10 +89,10 @@ jobs:
   notify_build:
     runs-on: ubuntu-latest
     needs: build-and-upload
-    if: always()  # Para asegurarse de enviar notificaciones tanto en caso de éxito como de fallo
+    if: always()
     steps:
       - name: Enviar notificación en caso de fallo
-        if: failure()  # Solo si falla
+        if: failure()
         uses: dawidd6/action-send-mail@v3
         with:
           server_address: ${{ secrets.MAIL_SERVER }}
@@ -108,7 +110,7 @@ jobs:
           from: ${{ secrets.MAIL_USERNAME }}
 
       - name: Enviar notificación en caso de éxito
-        if: success()  # Solo si es exitoso
+        if: success()
         uses: dawidd6/action-send-mail@v3
         with:
           server_address: ${{ secrets.MAIL_SERVER }}
